# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'session_screen.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import   

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(680, 400)
        MainWindow.setStyleSheet("QFrame {    \n"
"    background-color: rgb(56, 58, 89);    \n"
"    color: rgb(220, 220, 220);\n"
"    border-radius: 10px;\n"
"}")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QFrame(self.centralwidget)
        self.frame.setLayoutDirection(Qt.LeftToRight)
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_2 = QFrame(self.frame)
        self.frame_2.setMaximumSize(QSize(16777215, 20))
        self.frame_2.setLayoutDirection(Qt.RightToLeft)
        self.frame_2.setFrameShape(QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QHBoxLayout(self.frame_2)
        self.horizontalLayout.setContentsMargins(610, 0, 0, 1)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.closeButton = QPushButton(self.frame_2)
        self.closeButton.setMaximumSize(QSize(20, 20))
        font = QFont()
        font.setFamily("Small Fonts")
        self.closeButton.setFont(font)
        self.closeButton.setStyleSheet(".QPushButton {\n"
"    background-color:transparent;\n"
"    color: rgb(255, 255, 255);\n"
"    padding:16px 31px;\n"
"    text-decoration:none;\n"
"    text-align:center;\n"
"    vertical-align: middle;\n"
"}\n"
"\n"
".QPushButton:hover {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(255, 0, 0);\n"
"    border-radius:8px;\n"
"\n"
"}\n"
"")
        self.closeButton.setObjectName("closeButton")
        self.horizontalLayout.addWidget(self.closeButton)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.label_title = QLabel(self.frame)
        font = QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(40)
        self.label_title.setFont(font)
        self.label_title.setStyleSheet("color: rgb(254, 121, 199);")
        self.label_title.setAlignment(Qt.AlignCenter)
        self.label_title.setObjectName("label_title")
        self.verticalLayout_2.addWidget(self.label_title)
        self.label_running = QLabel(self.frame)
        self.label_running.setMaximumSize(QSize(16777215, 25))
        font = QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_running.setFont(font)
        self.label_running.setLayoutDirection(Qt.RightToLeft)
        self.label_running.setStyleSheet("color : rgb(98, 114, 164);")
        self.label_running.setAlignment(Qt.AlignCenter)
        self.label_running.setObjectName("label_running")
        self.verticalLayout_2.addWidget(self.label_running)
        self.label_status = QLabel(self.frame)
        sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_status.sizePolicy().hasHeightForWidth())
        self.label_status.setSizePolicy(sizePolicy)
        font = QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(36)
        self.label_status.setFont(font)
        self.label_status.setAlignment(Qt.AlignCenter)
        self.label_status.setObjectName("label_status")
        self.verticalLayout_2.addWidget(self.label_status)
        self.frame_3 = QFrame(self.frame)
        self.frame_3.setFrameShape(QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_2 = QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.endtask = QPushButton(self.frame_3)
        sizePolicy = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.endtask.sizePolicy().hasHeightForWidth())
        self.endtask.setSizePolicy(sizePolicy)
        self.endtask.setMaximumSize(QSize(200, 60))
        font = QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(20)
        self.endtask.setFont(font)
        self.endtask.setStyleSheet(".QPushButton {\n"
"    \n"
"    border-radius:15px;\n"
"    background-color: rgb(254, 121, 199);\n"
"    color:#ffffff;\n"
"    padding:16px 31px;\n"
"    text-decoration:none;\n"
"    color: rgb(98, 114, 164);\n"
"    border:2px solid rgb(98, 114, 164);\n"
"}\n"
"\n"
".QPushButton:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.426, x2:1, y2:0.46, stop:0 rgba(255, 0, 127, 255), stop:1 rgba(85, 0, 127, 255));\n"
"    color: rgb(255, 255, 255);\n"
"    border:2px solid rgb(200, 144, 200);\n"
"}\n"
"")
        self.endtask.setObjectName("endtask")
        self.horizontalLayout_2.addWidget(self.endtask)
        self.verticalLayout_2.addWidget(self.frame_3)
        self.gameCount = QLabel(self.frame)
        self.gameCount.setMaximumSize(QSize(16777215, 40))
        font = QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.gameCount.setFont(font)
        self.gameCount.setAlignment(Qt.AlignBottom|Qt.AlignHCenter)
        self.gameCount.setObjectName("gameCount")
        self.verticalLayout_2.addWidget(self.gameCount)
        self.label_copyright = QLabel(self.frame)
        self.label_copyright.setMaximumSize(QSize(16777215, 15))
        self.label_copyright.setStyleSheet("    color: rgb(98, 114, 164);")
        self.label_copyright.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_copyright.setObjectName("label_copyright")
        self.verticalLayout_2.addWidget(self.label_copyright)
        self.verticalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", "MainWindow"))
        self.closeButton.setText(QCoreApplication.translate("MainWindow", "X"))
        self.label_title.setText(QCoreApplication.translate("MainWindow", "<strong>Frux\'s</strong> BOT"))
        self.label_running.setText(QCoreApplication.translate("MainWindow", "Running..."))
        self.label_status.setText(QCoreApplication.translate("MainWindow", "<strong>Status </strong> : {}"))
        self.endtask.setText(QCoreApplication.translate("MainWindow", "STOP"))
        self.gameCount.setText(QCoreApplication.translate("MainWindow", "<strong>Game Count  </strong>: {}"))
        self.label_copyright.setText(QCoreApplication.translate("MainWindow", "©COPYRIGHT, FRUXC"))


if __name__ == "__main__":
    import sys
    app = QApplication(sys.argv)
    MainWindow = QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
