# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_activation_key.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import sys, os
import platform
from PySide2 import QtCore, QtGui, QtWidgets
from PySide2.QtCore import (QCoreApplication, QPropertyAnimation, QDate, QDateTime, QMetaObject, QObject, QPoint, QRect, QSize, QTime, QUrl, Qt, QEvent, QThread, Signal)
from PySide2.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont, QFontDatabase, QIcon, QKeySequence, QLinearGradient, QPalette, QPainter, QPixmap, QRadialGradient)
from PySide2.QtWidgets import *


class Ui_LicenseWindow(object):
    def setupUi(self, MainWindow):
        if MainWindow.objectName():
            MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedSize(680, 400)
        MainWindow.setStyleSheet("QFrame {    \n"
"    background-color: rgb(56, 58, 89);    \n"
"    color: rgb(220, 220, 220);\n"
"    border-radius: 10px;\n"
"}")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.body_frame = QFrame(self.centralwidget)
        self.body_frame.setStyleSheet("color : rgb(98, 114, 164);")
        self.body_frame.setFrameShape(QFrame.StyledPanel)
        self.body_frame.setFrameShadow(QFrame.Raised)
        self.body_frame.setObjectName("body_frame")
        self.verticalLayout_2 = QVBoxLayout(self.body_frame)
        self.verticalLayout_2.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.close_button_frame = QFrame(self.body_frame)
        self.close_button_frame.setMaximumSize(QSize(16777215, 20))
        self.close_button_frame.setFrameShape(QFrame.StyledPanel)
        self.close_button_frame.setFrameShadow(QFrame.Raised)
        self.close_button_frame.setObjectName("close_button_frame")
        self.horizontalLayout_2 = QHBoxLayout(self.close_button_frame)
        self.horizontalLayout_2.setContentsMargins(610, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.closeButton = QPushButton(self.close_button_frame)
        self.closeButton.setMaximumSize(QSize(20, 20))
        font = QFont()
        font.setFamily("Small Fonts")
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.closeButton.setFont(font)
        self.closeButton.setLayoutDirection(Qt.RightToLeft)
        self.closeButton.setStyleSheet(".QPushButton {\n"
"    background-color:transparent;\n"
"    color: rgb(255, 255, 255);\n"
"    padding:16px 31px;\n"
"    text-decoration:none;\n"
"    text-align:center;\n"
"    vertical-align: middle;\n"
"}\n"
"\n"
".QPushButton:hover {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(255, 0, 0);\n"
"    border-radius:8px;\n"
"\n"
"}\n"
"")
        self.closeButton.setCheckable(False)
        self.closeButton.setObjectName("closeButton")
        self.horizontalLayout_2.addWidget(self.closeButton)
        self.verticalLayout_2.addWidget(self.close_button_frame)
        self.label_title = QLabel(self.body_frame)
        self.label_title.setMinimumSize(QSize(0, 0))
        self.label_title.setMaximumSize(QSize(16777215, 80))
        font = QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(40)
        self.label_title.setFont(font)
        self.label_title.setStyleSheet("color: rgb(254, 121, 199);")
        self.label_title.setAlignment(Qt.AlignHCenter|Qt.AlignTop)
        self.label_title.setObjectName("label_title")
        self.verticalLayout_2.addWidget(self.label_title)
        self.label_key = QLabel(self.body_frame)
        self.label_key.setMaximumSize(QSize(16777215, 40))
        font = QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_key.setFont(font)
        self.label_key.setStyleSheet("color : rgb(98, 114, 164);")
        self.label_key.setAlignment(Qt.AlignHCenter|Qt.AlignTop)
        self.label_key.setObjectName("label_key")
        self.verticalLayout_2.addWidget(self.label_key)
        self.inputext_frame = QFrame(self.body_frame)
        self.inputext_frame.setMinimumSize(QSize(0, 90))
        self.inputext_frame.setFrameShape(QFrame.StyledPanel)
        self.inputext_frame.setFrameShadow(QFrame.Raised)
        self.inputext_frame.setObjectName("inputext_frame")
        self.verticalLayout_3 = QVBoxLayout(self.inputext_frame)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lineEdit = QLineEdit(self.inputext_frame)
        self.lineEdit.setMinimumSize(QSize(0, 80))
        font = QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("QLineEdit{\n"
"background-color:transparent;\n"
"border : 2px solid rgb(254, 121, 199);\n"
"border-radius: 10px;\n"
"padding: 0 8px;\n"
"\n"
"}")
        self.lineEdit.setAlignment(Qt.AlignCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_3.addWidget(self.lineEdit)
        self.button_frame = QFrame(self.inputext_frame)
        self.button_frame.setFrameShape(QFrame.StyledPanel)
        self.button_frame.setFrameShadow(QFrame.Raised)
        self.button_frame.setObjectName("button_frame")
        self.horizontalLayout = QHBoxLayout(self.button_frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.check_button = QPushButton(self.button_frame)
        sizePolicy = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.check_button.sizePolicy().hasHeightForWidth())
        self.check_button.setSizePolicy(sizePolicy)
        self.check_button.setMaximumSize(QSize(200, 16777215))
        font = QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.check_button.setFont(font)
        self.check_button.setLayoutDirection(Qt.LeftToRight)
        self.check_button.setStyleSheet(".QPushButton {\n"
"    border-radius:15px;\n"
"    background-color: rgb(254, 121, 199);\n"
"    color:#ffffff;\n"
"    padding:16px 31px;\n"
"    text-decoration:none;\n"
"    color: rgb(98, 114, 164);\n"
"    border:2px solid rgb(98, 114, 164);\n"
"}\n"
"\n"
".QPushButton:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.426, x2:1, y2:0.46, stop:0 rgba(255, 0, 127, 255), stop:1 rgba(85, 0, 127, 255));\n"
"    color: rgb(255, 255, 255);\n"
"    border:2px solid rgb(200, 144, 200);\n"
"}\n"
"")
        self.check_button.setObjectName("check_button")
        self.horizontalLayout.addWidget(self.check_button)
        self.verticalLayout_3.addWidget(self.button_frame)
        self.verticalLayout_2.addWidget(self.inputext_frame)
        self.label_copyright = QLabel(self.body_frame)
        self.label_copyright.setMaximumSize(QSize(16777215, 15))
        font = QFont()
        font.setFamily("Segoe UI")
        self.label_copyright.setFont(font)
        self.label_copyright.setStyleSheet("    color: rgb(98, 114, 164);")
        self.label_copyright.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_copyright.setObjectName("label_copyright")
        self.verticalLayout_2.addWidget(self.label_copyright)
        self.verticalLayout.addWidget(self.body_frame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.closeButton.setText(_translate("MainWindow", "X"))
        self.label_title.setText(_translate("MainWindow", "<strong>Frux\'s</strong> BOT"))
        self.label_key.setText(_translate("MainWindow", "--ACTIVATION KEY--"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "ENTER KEY HERE"))
        self.check_button.setText(_translate("MainWindow", "ACTIVATE"))
        self.label_copyright.setText(_translate("MainWindow", "©COPYRIGHT, FRUXC"))

